hi
The thrown exception was: foo
done!